#!/usr/bin/env python
from os import getcwd, listdir, remove
from os.path import expanduser, join
from shutil import copyfile
from subprocess import call

cwd = getcwd()
src = join(expanduser("~"), ".re1", "templates", "tex")

copyfile(join(src, "makefile"), join(cwd, "makefile"))
copyfile(join(src, ".lst.tex"), join(cwd, ".lst.tex"))

files = [join(cwd, f) for f in listdir(cwd) if join(cwd, f).endswith(".tex")]
templates = ["school", "science"]
found = []

for name in files:
    with open(name) as f:
        for line in f:
            if "\documentclass" in line:
                for t in templates:
                    if "{%s}" % t in line:
                        found.append(t)
                        templates.remove(t)
                break
    if not templates:
        break

for t in found:
    copyfile(join(src, t, f"{t}.cls"), join(cwd, f"{t}.cls"))

# Call GNU Make in the current directory
call("make")

# Clean up
tmp = [join(cwd, ".lst.tex"),
       join(cwd, "makefile"),
       join(cwd, "school.cls"),
       join(cwd, "science.cls")]

for f in tmp:
    try:
        remove(f)
    except OSError:
        pass
