#!/usr/bin/env python
import sys
from getopt import getopt, GetoptError
from os import getcwd, listdir, remove
from os.path import expanduser, join, isdir
from shutil import copyfile
from subprocess import call


def usage():
    print("-f  --file\tFile to compile")
    print("-h  --help\tShow a useful help menu")
    print("-l  --log\tSpare log files during cleanup")
    print("-o  --odt\tBuild to odt instead of pdf")


if __name__ == "__main__":
    make = ["make"]

    try:
        opts, args = getopt(sys.argv[1:], "f:hlm:o", ["file", "help", "log", "make", "odt"])
    except GetoptError:
        usage()
        sys.exit(2)

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        if opt in ("-m", "--make"):
            make += arg.split(" ")
        if opt in ("-f", "--file"):
            make.append("f=" + arg)
        if opt in ("-s", "--simple"):
            make.append("pdf")
        if opt in ("-o", "--odt"):
            make.append("odt")
        if opt in ("-l", "--log"):
            make.append("LOG=true")

    cwd = getcwd()
    src = join(expanduser("~"), ".re1", "templates", "tex")

    copyfile(join(src, "makefile"), join(cwd, "makefile"))
    copyfile(join(src, ".lst.tex"), join(cwd, ".lst.tex"))

    files = [join(cwd, f) for f in listdir(cwd) if join(cwd, f).endswith(".tex")]
    templates = [d for d in listdir(src) if isdir(join(src, d))]
    found = []

    for name in files:
        with open(name) as f:
            for line in f:
                if "\documentclass" in line:
                    template = line[line.index("{")+1:line.index("}")]
                    for t in templates:
                        if template == t:
                            found.append(t)
                            templates.remove(t)
                            break
                    break
        if not templates:
            break

    for t in found:
        copyfile(join(src, t, f"{t}.cls"), join(cwd, f"{t}.cls"))

    # Call GNU Make in the current directory
    call(tuple(make))

    # Clean up
    tmp = [join(cwd, ".lst.tex"),
           join(cwd, "makefile"),
           join(cwd, "school.cls"),
           join(cwd, "science.cls")]

    for f in tmp:
        try:
            remove(f)
        except OSError:
            pass
